"""Add Excel import center tables

Revision ID: 20260718_0002
Revises: 20260717_0001
Create Date: 2026-07-18 09:07:20.366523
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260718_0002'
down_revision: Union[str, None] = '20260717_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('specification', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=40), nullable=False),
    sa.Column('import_type', sa.String(length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=100), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('workbook_sheet_count', sa.Integer(), nullable=False),
    sa.Column('selected_sheet_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('warning_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('field_mapping', sa.JSON(), nullable=True),
    sa.Column('import_options', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_import_batches_batch_no'), 'import_batches', ['batch_no'], unique=True)
    op.create_index(op.f('ix_import_batches_created_by'), 'import_batches', ['created_by'], unique=False)
    op.create_index(op.f('ix_import_batches_file_sha256'), 'import_batches', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_import_batches_import_type'), 'import_batches', ['import_type'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_table('fitting_wip_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('production_batch_no', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitting_wip_snapshots_import_batch_id'), 'fitting_wip_snapshots', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_fitting_wip_snapshots_product_id'), 'fitting_wip_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_fitting_wip_snapshots_production_batch_no'), 'fitting_wip_snapshots', ['production_batch_no'], unique=False)
    op.create_index(op.f('ix_fitting_wip_snapshots_snapshot_date'), 'fitting_wip_snapshots', ['snapshot_date'], unique=False)
    op.create_table('import_row_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('excel_row_number', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('issue_code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_row_issues_excel_row_number'), 'import_row_issues', ['excel_row_number'], unique=False)
    op.create_index(op.f('ix_import_row_issues_import_batch_id'), 'import_row_issues', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_import_row_issues_issue_code'), 'import_row_issues', ['issue_code'], unique=False)
    op.create_index(op.f('ix_import_row_issues_severity'), 'import_row_issues', ['severity'], unique=False)
    op.create_table('imported_weekly_plan_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('production_batch_no', sa.String(length=100), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('equipment_name', sa.String(length=100), nullable=False),
    sa.Column('plan_start_date', sa.Date(), nullable=True),
    sa.Column('plan_end_date', sa.Date(), nullable=True),
    sa.Column('planned_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_weekly_plan_raw_import_batch_id'), 'imported_weekly_plan_raw', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_imported_weekly_plan_raw_product_id'), 'imported_weekly_plan_raw', ['product_id'], unique=False)
    op.create_index(op.f('ix_imported_weekly_plan_raw_production_batch_no'), 'imported_weekly_plan_raw', ['production_batch_no'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('on_hand_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expected_inbound_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expected_outbound_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_available_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('calculated_available_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_snapshots_import_batch_id'), 'inventory_snapshots', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_product_id'), 'inventory_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_snapshot_date'), 'inventory_snapshots', ['snapshot_date'], unique=False)
    op.create_table('pipe_wip_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipe_wip_snapshots_import_batch_id'), 'pipe_wip_snapshots', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_pipe_wip_snapshots_product_id'), 'pipe_wip_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_pipe_wip_snapshots_snapshot_date'), 'pipe_wip_snapshots', ['snapshot_date'], unique=False)
    op.create_table('regular_production_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regular_production_products_import_batch_id'), 'regular_production_products', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_regular_production_products_product_id'), 'regular_production_products', ['product_id'], unique=False)
    op.create_table('shipment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('document_no', sa.String(length=100), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('shipment_month', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('production_batch_no', sa.String(length=100), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_batch_id', 'source_sheet', 'source_row_number')
    )
    op.create_index(op.f('ix_shipment_records_document_no'), 'shipment_records', ['document_no'], unique=False)
    op.create_index(op.f('ix_shipment_records_import_batch_id'), 'shipment_records', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_shipment_records_product_id'), 'shipment_records', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_records_product_id'), table_name='shipment_records')
    op.drop_index(op.f('ix_shipment_records_import_batch_id'), table_name='shipment_records')
    op.drop_index(op.f('ix_shipment_records_document_no'), table_name='shipment_records')
    op.drop_table('shipment_records')
    op.drop_index(op.f('ix_regular_production_products_product_id'), table_name='regular_production_products')
    op.drop_index(op.f('ix_regular_production_products_import_batch_id'), table_name='regular_production_products')
    op.drop_table('regular_production_products')
    op.drop_index(op.f('ix_pipe_wip_snapshots_snapshot_date'), table_name='pipe_wip_snapshots')
    op.drop_index(op.f('ix_pipe_wip_snapshots_product_id'), table_name='pipe_wip_snapshots')
    op.drop_index(op.f('ix_pipe_wip_snapshots_import_batch_id'), table_name='pipe_wip_snapshots')
    op.drop_table('pipe_wip_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_snapshot_date'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_product_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_import_batch_id'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_imported_weekly_plan_raw_production_batch_no'), table_name='imported_weekly_plan_raw')
    op.drop_index(op.f('ix_imported_weekly_plan_raw_product_id'), table_name='imported_weekly_plan_raw')
    op.drop_index(op.f('ix_imported_weekly_plan_raw_import_batch_id'), table_name='imported_weekly_plan_raw')
    op.drop_table('imported_weekly_plan_raw')
    op.drop_index(op.f('ix_import_row_issues_severity'), table_name='import_row_issues')
    op.drop_index(op.f('ix_import_row_issues_issue_code'), table_name='import_row_issues')
    op.drop_index(op.f('ix_import_row_issues_import_batch_id'), table_name='import_row_issues')
    op.drop_index(op.f('ix_import_row_issues_excel_row_number'), table_name='import_row_issues')
    op.drop_table('import_row_issues')
    op.drop_index(op.f('ix_fitting_wip_snapshots_snapshot_date'), table_name='fitting_wip_snapshots')
    op.drop_index(op.f('ix_fitting_wip_snapshots_production_batch_no'), table_name='fitting_wip_snapshots')
    op.drop_index(op.f('ix_fitting_wip_snapshots_product_id'), table_name='fitting_wip_snapshots')
    op.drop_index(op.f('ix_fitting_wip_snapshots_import_batch_id'), table_name='fitting_wip_snapshots')
    op.drop_table('fitting_wip_snapshots')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_import_type'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_file_sha256'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_created_by'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_batch_no'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
