"""Harden phase 2 import review flows

Revision ID: 20260718_0003
Revises: 20260718_0002
Create Date: 2026-07-18 10:16:08.527249
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260718_0003'
down_revision: Union[str, None] = '20260718_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plan_staging_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name_raw', sa.String(length=255), nullable=True),
    sa.Column('specification_raw', sa.String(length=255), nullable=True),
    sa.Column('production_batch_no', sa.String(length=100), nullable=True),
    sa.Column('process_name', sa.String(length=100), nullable=True),
    sa.Column('equipment_name', sa.String(length=100), nullable=True),
    sa.Column('plan_start_date', sa.Date(), nullable=False),
    sa.Column('plan_end_date', sa.Date(), nullable=False),
    sa.Column('daily_plan', sa.JSON(), nullable=False),
    sa.Column('daily_actual', sa.JSON(), nullable=False),
    sa.Column('weekly_plan_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('weekly_actual_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('formula_metadata', sa.JSON(), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('matched_product_id', sa.Integer(), nullable=True),
    sa.Column('matched_by', sa.Integer(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['matched_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plan_staging_rows_import_batch_id'), 'weekly_plan_staging_rows', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_weekly_plan_staging_rows_match_status'), 'weekly_plan_staging_rows', ['match_status'], unique=False)
    op.create_index(op.f('ix_weekly_plan_staging_rows_matched_product_id'), 'weekly_plan_staging_rows', ['matched_product_id'], unique=False)
    op.create_index(op.f('ix_weekly_plan_staging_rows_plan_end_date'), 'weekly_plan_staging_rows', ['plan_end_date'], unique=False)
    op.create_index(op.f('ix_weekly_plan_staging_rows_plan_start_date'), 'weekly_plan_staging_rows', ['plan_start_date'], unique=False)
    op.create_index(op.f('ix_weekly_plan_staging_rows_production_batch_no'), 'weekly_plan_staging_rows', ['production_batch_no'], unique=False)
    op.add_column('imported_weekly_plan_raw', sa.Column('daily_plan', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('imported_weekly_plan_raw', sa.Column('daily_actual', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    with op.batch_alter_table('products') as batch_op:
        batch_op.add_column(sa.Column('last_import_batch_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_products_last_import_batch_id'), ['last_import_batch_id'], unique=False)
        batch_op.create_foreign_key('fk_products_last_import_batch_id', 'import_batches', ['last_import_batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_constraint('fk_products_last_import_batch_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_products_last_import_batch_id'))
        batch_op.drop_column('last_import_batch_id')
    op.drop_column('imported_weekly_plan_raw', 'daily_actual')
    op.drop_column('imported_weekly_plan_raw', 'daily_plan')
    op.drop_index(op.f('ix_weekly_plan_staging_rows_production_batch_no'), table_name='weekly_plan_staging_rows')
    op.drop_index(op.f('ix_weekly_plan_staging_rows_plan_start_date'), table_name='weekly_plan_staging_rows')
    op.drop_index(op.f('ix_weekly_plan_staging_rows_plan_end_date'), table_name='weekly_plan_staging_rows')
    op.drop_index(op.f('ix_weekly_plan_staging_rows_matched_product_id'), table_name='weekly_plan_staging_rows')
    op.drop_index(op.f('ix_weekly_plan_staging_rows_match_status'), table_name='weekly_plan_staging_rows')
    op.drop_index(op.f('ix_weekly_plan_staging_rows_import_batch_id'), table_name='weekly_plan_staging_rows')
    op.drop_table('weekly_plan_staging_rows')
    # ### end Alembic commands ###
