<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { cancelProductionDemand, listProductionDemands, type ProductionDemand } from '../api/replenishment'
import { useAuthStore } from '../stores/auth'

const auth = useAuthStore(); const loading = ref(false); const items = ref<ProductionDemand[]>([]); const total = ref(0)
const filters = reactive({ keyword: '', status: '', page: 1, page_size: 50 })
const canCancel = computed(() => auth.hasPermission('demand.cancel'))
async function refresh(){loading.value=true;try{const result=await listProductionDemands({...filters,keyword:filters.keyword||undefined,status:filters.status||undefined});items.value=result.items;total.value=result.total}finally{loading.value=false}}
async function cancel(row:ProductionDemand){const {value}=await ElMessageBox.prompt('取消后需求不会物理删除，请填写原因','取消生产需求',{inputValue:'业务确认取消'});try{await cancelProductionDemand(row.id,value);ElMessage.success('需求已取消并记录审计');await refresh()}catch(error:any){ElMessage.error(error?.response?.data?.message??'取消失败')}}
onMounted(refresh)
</script>
<template><section class="demand-page"><div class="heading"><div><span>PRODUCTION DEMAND POOL</span><h2>生产需求池</h2><p>阶段 3 仅管理待排需求及来源证据，不创建排产任务。</p></div></div><el-card shadow="never"><el-form inline><el-input v-model="filters.keyword" placeholder="需求号/产品编码/名称" clearable style="width:260px"/><el-select v-model="filters.status" clearable placeholder="状态" style="width:180px"><el-option value="PENDING_SCHEDULE"/><el-option value="CANCELLED"/></el-select><el-button @click="refresh">查询</el-button></el-form><el-table v-loading="loading" :data="items"><el-table-column prop="demand_no" label="需求编号" fixed width="170"/><el-table-column prop="product_code" label="产品编码" width="150"/><el-table-column prop="product_name" label="名称" min-width="150"/><el-table-column prop="specification" label="规格" width="140"/><el-table-column prop="unit" label="单位" width="75"/><el-table-column prop="confirmed_qty" label="确认量" width="110"/><el-table-column prop="active_allocated_qty" label="已分配" width="100"/><el-table-column prop="remaining_to_schedule_qty" label="剩余待排" width="110"/><el-table-column prop="qualified_completed_qty" label="完成量" width="100"/><el-table-column prop="remaining_to_complete_qty" label="剩余待完成" width="120"/><el-table-column prop="source_run_no" label="来源补库运行" width="180"/><el-table-column prop="source_suggestion_id" label="来源建议" width="100"/><el-table-column prop="priority" label="优先级" width="80"/><el-table-column prop="required_date" label="要求日期" width="115"/><el-table-column prop="status" label="状态" width="150"/><el-table-column prop="created_at" label="创建时间" width="170"/><el-table-column v-if="canCancel" label="操作" fixed="right" width="90"><template #default="{row}"><el-button link type="danger" :disabled="row.status==='CANCELLED'||Number(row.active_allocated_qty)>0" @click="cancel(row)">取消</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="filters.page" v-model:page-size="filters.page_size" :total="total" @change="refresh"/></el-card></section></template>
<style scoped>.demand-page{display:grid;gap:18px}.heading span{color:#75914f;font-size:10px;font-weight:800;letter-spacing:.18em}.heading h2{margin:5px 0;font-size:26px}.heading p{margin:0;color:#6b7971}.el-pagination{margin-top:18px;justify-content:flex-end}</style>
